/**
 * AppDatabase.kt - Room database definition for the Signal Backup app.
 *
 * This file defines the Room database that serves as the local SQLite persistence layer.
 * Room is an abstraction layer over SQLite that provides compile-time verification of
 * SQL queries, eliminates boilerplate code, and integrates with Kotlin coroutines and Flow.
 *
 * Architecture context:
 * - This is the top-level database definition in the **data layer**.
 * - It lists all entities (tables) and provides accessor methods for each DAO.
 * - A single AppDatabase instance is created as a singleton by Hilt (in AppModule)
 *   and shared across the entire app.
 *
 * Key Room annotations:
 * - [@Database]: Declares this as a Room database, listing all entity classes and
 *   the schema version number.
 * - `exportSchema = false`: Disables schema export to JSON files (used for migration
 *   testing in production apps, but not needed for this v1 app).
 *
 * @see data.local.entity.UploadHistoryEntity for the table schema
 * @see data.local.db.UploadHistoryDao for the data access methods
 * @see di.AppModule for how this database is instantiated as a Hilt singleton
 */
package com.johnsonyuen.signalbackup.data.local.db

import androidx.room.Database
import androidx.room.RoomDatabase
import com.johnsonyuen.signalbackup.data.local.entity.UploadHistoryEntity

/**
 * The Room database for Signal Backup.
 *
 * Currently contains a single table (upload_history) at schema version 1.
 * If you add new entities or modify existing ones, you must increment the version
 * number and provide a migration strategy (or use fallbackToDestructiveMigration
 * during development).
 *
 * Room requires this to be an abstract class extending [RoomDatabase]. The actual
 * implementation is generated by Room's annotation processor (KSP) at compile time.
 */
@Database(
    entities = [UploadHistoryEntity::class],
    version = 2,
    exportSchema = false,
)
abstract class AppDatabase : RoomDatabase() {

    /**
     * Provides access to upload history database operations.
     *
     * Room generates the DAO implementation and wires it to this database instance.
     * The actual DAO object is obtained through this method and then provided to
     * the dependency graph via AppModule.provideUploadHistoryDao().
     */
    abstract fun uploadHistoryDao(): UploadHistoryDao
}
