/**
 * UploadHistoryDao.kt - Room Data Access Object for the upload_history table.
 *
 * This interface defines the SQL operations available for the upload history table.
 * Room generates the implementation at compile time based on the annotations and
 * SQL queries defined here. This is the **only** way the app reads from or writes
 * to the upload_history table.
 *
 * Architecture context:
 * - Part of the **data layer** (data/local/db package).
 * - Used exclusively by [UploadHistoryRepositoryImpl], which wraps it behind the
 *   [UploadHistoryRepository] interface for clean architecture separation.
 * - Injected by Hilt via AppModule's `provideUploadHistoryDao()` method.
 *
 * Key Room/Kotlin patterns:
 * - `suspend fun` methods run on a background thread via Room's built-in coroutine support.
 * - `Flow` return types create reactive queries that automatically re-emit whenever
 *   the underlying data changes (e.g., after a new insert), enabling the UI to
 *   update in real-time without manual refresh.
 *
 * @see data.local.entity.UploadHistoryEntity for the table schema
 * @see data.repository.UploadHistoryRepositoryImpl for the repository that wraps this DAO
 */
package com.johnsonyuen.signalbackup.data.local.db

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import com.johnsonyuen.signalbackup.data.local.entity.UploadHistoryEntity
import kotlinx.coroutines.flow.Flow

/**
 * Data Access Object for upload history database operations.
 *
 * [@Dao] tells Room to generate an implementation of this interface at compile time.
 * Each method maps to a specific SQL operation.
 */
@Dao
interface UploadHistoryDao {

    /**
     * Inserts a new upload history record into the database.
     *
     * This is a `suspend` function because database writes are I/O operations that
     * should not block the main thread. Room automatically runs this on a background
     * thread within the coroutine context.
     *
     * @param entity The upload record to insert. The `id` field (if 0) will be
     *        auto-generated by SQLite.
     */
    @Insert
    suspend fun insert(entity: UploadHistoryEntity)

    /**
     * Returns all upload history records, ordered newest-first.
     *
     * Returns a [Flow] so that the UI (HistoryScreen) can reactively observe changes.
     * Whenever a new record is inserted, Room automatically re-queries and emits the
     * updated list through this Flow -- no manual refresh needed.
     *
     * @return A Flow emitting the complete list of records, re-emitted on any table change.
     */
    @Query("SELECT * FROM upload_history ORDER BY timestamp DESC")
    fun getAll(): Flow<List<UploadHistoryEntity>>

    /**
     * Returns the most recent upload history record, or null if the table is empty.
     *
     * Used by the home screen to show the latest upload status. Like [getAll], this
     * returns a Flow for reactive observation.
     *
     * @return A Flow emitting the latest record (or null), re-emitted on any table change.
     */
    @Query("SELECT * FROM upload_history ORDER BY timestamp DESC LIMIT 1")
    fun getLatest(): Flow<UploadHistoryEntity?>
}
